resolver: lts-12.2

packages:
- '.'

flags: {}

extra-deps:
- tasty-rerun-1.1.12
#- './liquid-fixpoint/'
# liquid-fixpoint and deps
- github: ucsd-progsys/liquid-fixpoint
  commit: abb35956cde1ab7c194b9b63e0d6ec977fbab754
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.2
- located-base-0.1.1.1
- text-format-0.3.2

extra-package-dbs: []
